name: 构建和发布

on:
  workflow_dispatch:
    inputs:
      version:
        description: 版本号 (不带v)
        required: true
        default: 2.3.3
  release:
    types: [published]

permissions: {}

jobs:
  build:
    name: 打包压缩包和安装程序
    runs-on: windows-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: 配置 Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: 3.x

      - name: 更新版本号
        shell: pwsh
        env:
          PYTHONIOENCODING: utf-8
          GITHUB_EVENT_INPUTS_VERSION: ${{ github.event.inputs.version }}
        # 前面已经配置过 Python 了，这个脚本只用 os 和 sys 这两个标准库，不用再装依赖
        run: |-
          if ($env:GITHUB_EVENT_NAME -eq "workflow_dispatch") {
            $version = "$env:GITHUB_EVENT_INPUTS_VERSION"
            # 如果版本号以 v 开头，则去掉 v
            if ($version.StartsWith("v")) {
              $version = $version.Substring(1)
            }
          } else {
            $version = "$env:GITHUB_REF_NAME"
            # 如果版本号以 refs/tags/ 开头，则去掉 refs/tags/
            if ($version.StartsWith("refs/tags/")) {
              $version = $version.Substring(10)
            }
            # 如果版本号以 v 开头，则去掉 v
            if ($version.StartsWith("v")) {
              $version = $version.Substring(1)
            }
          }
          Write-Host "Version: $version"
          python "自动化脚本/修改版本号.py" "$version"

      - name: 安装依赖
        shell: pwsh
        env:
          PYTHONIOENCODING: utf-8
        # 环境配置的依赖文件中含有打包所需依赖
        run: |-
          pip install -r "requirements.txt"
          pip list
          Write-Host "=================UPX===================="
          $upx_url = (Invoke-WebRequest -Uri https://api.github.com/repos/upx/upx/releases/latest).Content | ConvertFrom-Json | Select-Object -ExpandProperty assets | Where-Object { $_.name -like "*win64.zip" } | Select-Object -ExpandProperty browser_download_url
          Write-Host "[INFO] Latest UPX download URL: $upx_url"
          Invoke-WebRequest -Uri $upx_url -OutFile "upx-latest.zip"
          7z x "upx-latest.zip" -o"upx"
          $upx_version = (Get-ChildItem -Path "upx" -Directory | Sort-Object Name -Descending | Select-Object -First 1).Name
          Move-Item "upx\$upx_version\*" "upx" -Verbose
          Remove-Item "upx\$upx_version" -Verbose -Recurse
          Remove-Item "upx-latest.zip" -Verbose
          tree /a /f

      - name: 整理源码
        # 整理文件 > 压缩文件 > 清理工作目录
        env:
          PYTHONIOENCODING: utf-8
        shell: pwsh
        run: |-
          Copy-Item -Path "LICENSE" -Destination "src/LICENSE" -Verbose
          New-Item -ItemType Directory -Path "Release" -Verbose
          New-Item -ItemType Directory -Path "Release/src" -Verbose
          Copy-Item -Recurse -Path "src/*" -Destination "Release/src"
          Copy-Item -Path "LICENSE" -Destination "Release/src" -Verbose
          Copy-Item -Path "requirements.txt" -Destination "Release/src" -Verbose
          # 压缩源码到 Release，7z 和 zip
          7z a -t7z Release/Sundry-src.7z Release/src
          7z a -tzip Release/Sundry-src.zip Release/src

      - name: 制作安装程序和打包后的压缩包
        shell: pwsh
        env:
          PYTHONIOENCODING: utf-8
        # 这里是直接打包过去的，不用管 sundry.ps1
        run: |-
          New-Item -ItemType Directory -Path "Release/pack" -Verbose
          Copy-Item -Path "src/fun.txt" -Destination "Release/pack" -Verbose
          Copy-Item -Path "LICENSE" -Destination "Release/pack" -Verbose
          Write-Host "========================================"
          python "自动化脚本/png-2-ico.py"
          pyinstaller --onefile --distpath="Release/pack" --name="sundry.exe" "src/sundry.py" --upx-dir="upx" -i "icon/Sundry.ico"
          Write-Host "========================================"
          7z a -t7z Release/Sundry.7z Release/pack
          7z a -tzip Release/Sundry.zip Release/pack
          Write-Host "========================================"
          curl -o "C:\Program Files (x86)\Inno Setup 6\Languages\ChineseSimplified.isl" "https://raw.githubusercontent.com/jrsoftware/issrc/main/Files/Languages/Unofficial/ChineseSimplified.isl"
          iscc installer.iss

      - name: 上传构建文件
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Release
          path: Release/**

  publish:
    name: 发布发行版
    needs: build
    runs-on: windows-latest
    if: ${{ github.event_name == 'release' }}

    permissions:
      contents: write # 发布发行版

    steps:
      - name: 下载构建文件
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: Release
          path: Release

      - name: 移除中间产物
        shell: pwsh
        run: |-
          Remove-Item -Recurse "Release/pack" -Verbose
          Remove-Item -Recurse "Release/src" -Verbose

      - name: 发布至发行版
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          files: Release/**
